baseurl: https://themesfromart.com
title: 'Themes from Art: Poems, Paintings, Pop and Pictures'
author: 'Rees Morrison'
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.png
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
  progressively: no
  sitename: Themes from Art
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Themes
      url: /posts/
      weight: 2
    - name: About
      url: /about/
      weight: 1
    - name: GitHub
      url: https://github.com/ReesMorrison/BlogThemes
      weight: 3
    - name: Twitter
      url: https://twitter.com/@ReesMorrison
      weight: 4
    - name: Subscribe
      url: /index.xml
      weight: 5

taxonomies:
    category: categories
    
# disqusShortname:

# googleAnalytics: G-47YEDDNJBK